### ISSUE TITLE
🐛 Ich verstehe das Front-End-Token nicht

### ISSUE THREAD

**Issue by Speetal** [tjarbo/discord-moodle-bot#71]
### Beschreibe den Bug
Ich habe das ganze Wiki buchstabengetreu befolgt, ich habe es mehrmals gemacht, um sicherzugehen, dass ich keinen Fehler gemacht habe. Ich habe die .env-Datei angepasst, ich habe den Discord-Bot auf den Server und in den richtigen Kanal gesetzt.

Sobald die Installation abgeschlossen ist, gehe ich zum Frontend. Ich gebe meinen Discord-Nickname ein, klicke auf "Token anforden", bekomme die Meldung "Token wurde erfolgreich versendet". Dennoch passiert nichts. Ich verstehe nicht, wie man das macht, weil dieser Schritt nicht im Wiki steht.

Können Sie mir helfen?

Danke

I followed the whole wiki, I did it several times to make sure I didn't make a mistake. I adapted the .env file, I put the Discord bot on the server and in the right channel.

Once the installation is finished, I go to the Front-End. I enter my Discord nickname, I click on "Token Anforden", I get the message "Token wurde erfolgreich versendet". Yet nothing happens. I don't understand how to do this because this step is not on the wiki.

Can you help me?

Thanks

### Schritte zum Reproduzieren:
1. Installieren mit Docker
2. Gehen Sie zu localhost

### Was sollte eigentlich passieren?
Unmöglich zu wissen, wie man das Token für die Anmeldung abruft.

### Weiteres:
Die Protokolle von `sudo docker logs fmdb` :

> UnauthorizedError: No authorization token was found
    at middleware (/usr/src/app/packages/backend/node_modules/express-jwt/lib/index.js:79:21)
    at Layer.handle [as handle_request] (/usr/src/app/packages/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/src/app/packages/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:174:3)
(node:1) UnhandledPromiseRejectionWarning: #<ApiError>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[object Object]
UnauthorizedError: No authorization token was found
    at middleware (/usr/src/app/packages/backend/node_modules/express-jwt/lib/index.js:79:21)
    at Layer.handle [as handle_request] (/usr/src/app/packages/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/src/app/packages/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/packages/backend/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/src/app/packages/backend/node_modules/express/lib/router/index.js:174:3)
(node:1) UnhandledPromiseRejectionWarning: #<ApiError>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Umgebung(please complete the following information):**
 - OS: [Linux - Pop!_OS]
 - Browser [Brave and Firefox]
 - Version [?]

**Comment by tjarbo** [comment]
Moin :wave: 
vielen Dank, dass du ein Issue aufgemacht hast und sogar gleich den Error-Log mitgeschickt hast :+1:

Ich vermute, dass es sich dabei um ein bekanntes Problem handelt: Das Problem ist, dass der Bot momentan nur an "bekannte" Channels und Nutzern Nachrichten verschicken kann. Ist vermutlich eine Einschränkung von Discord um Spambots zu verhindern, aber da haben wir noch nicht weiter geforscht. Um dich also in den Cache des Bots einzutragen, reicht es, wenn du diesem eine kleine "test" Nachricht schickst. Das selbe sollte auch im Channel erfolgen - der Bot muss natürlich die notwendigen Berechtigungen haben um Nachrichten zu lesen. Vielleicht kannst du auch zwei Fliegen mit einer Klappen schlagen und eine "Test" Nachricht im Channel reicht aus, um dich und den Channel in den Cache einzutragen, aber dafür keine Garantie :smile: 

Ich weiß leider nicht, an welcher Stelle dieser Hinweis verloren gegangen ist :thinking: Versuche ihn zeitnah im Wiki nachzutragen.
